# Setup
title:               망고 블로그
tagline:             'A Jekyll theme'
description:         '인공지능, 딥러닝, 논문 리뷰하는 개발자'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Inhak LEE
  url:               https://naknaklee.github.io
  email:             inhak4488@gmail.com
  github:            https://github.com/naknaklee

# Gems
plugins:
  - jekyll-paginate

# OpenGraph
opengraph_type:      website

# Custom vars
version:             1.1.0
google_analytics_id: G-1T8DEECHG0
