# Setup
title:               망고 블로그
tagline:             'A Jekyll theme'
description:         '인공지능, 딥러닝, 논문 리뷰하는 개발자'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark ㅇㅁㄴㄹ넘ㅇㄹ
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com
  github:            https://github.com/naknaklee

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-1T8DEECHG0
